meta_product_name: "Pregnant in Berlin"
meta_title: "Pregnant in Berlin - Helping expecting parents in Berlin"
meta_description: "Pregnant in Berlin's first aim is to help foreign couples expecting a child to find their way in the German system concerning pregnancy and child care."
meta_image: "cover.png"
